# Generated by Django 3.0.5 on 2020-04-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200427_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home2',
            new_name='home_db',
        ),
    ]
